//
// Created by Ruurd Adema on 21/06/2022.
//

#include <spdlog/spdlog.h>

#include <HelloWorld_generated.h>

int main()
{
    SPDLOG_INFO("Added some log statements to show usage of spdlog and fmt through Conan");

    // This is an object generated by the Flatbuffers object api (--gen-object-api).
    flat::HelloWorldT helloWorld;

    helloWorld.messages.emplace_back("Hello World 1");
    helloWorld.messages.emplace_back("Hello World 2");

    flatbuffers::FlatBufferBuilder flatBufferBuilder;
    flatBufferBuilder.Finish(flat::HelloWorld::Pack(flatBufferBuilder, &helloWorld));

    // At this point the data exists as serialized inside flatBufferBuilder. Let's verify and deserialize it.

    auto verifier = flatbuffers::Verifier(flatBufferBuilder.GetBufferPointer(), flatBufferBuilder.GetSize());

    if (!verifier.VerifyBuffer<flat::HelloWorld>(nullptr)) {
        SPDLOG_ERROR("Invalid buffer");
        return -1;
    }

    flat::HelloWorldT helloWorld2;
    flatbuffers::GetRoot<flat::HelloWorld>(flatBufferBuilder.GetBufferPointer())->UnPackTo(&helloWorld2);

    for (auto& msg: helloWorld2.messages) {
        SPDLOG_INFO("Message: {}", msg);
    }
}
